In [3]:
import pandas as pd
import numpy as np
import json
import pickle
from xgboost import XGBClassifier

In [4]:
# Load the model object from the file
with open('wine_model.h5', 'rb') as file:
    loaded_model = pickle.load(file)

In [9]:
#Export to csv file for Tableau
df=pd.read_csv("combined_datasets.csv")
df = df.drop(["wine_type", "quality"], axis=1) # keep ALL features except for the target

df.head()

fixed_acidity  volatile_acidity  citric_acid  residual_sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free_sulfur_dioxide  total_sulfur_dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  
0      9.4  
1      9.8  
2      9.8  
3      9.8  
4      9.4

In [11]:
df.columns

Index(['fixed_acidity', 'volatile_acidity', 'citric_acid', 'residual_sugar',
       'chlorides', 'free_sulfur_dioxide', 'total_sulfur_dioxide', 'density',
       'pH', 'sulphates', 'alcohol'],
      dtype='object')

In [12]:
df.iloc[0]

fixed_acidity            7.4000
volatile_acidity         0.7000
citric_acid              0.0000
residual_sugar           1.9000
chlorides                0.0760
free_sulfur_dioxide     11.0000
total_sulfur_dioxide    34.0000
density                  0.9978
pH                       3.5100
sulphates                0.5600
alcohol                  9.4000
Name: 0, dtype: float64

In [13]:
df.iloc[0].values

array([ 7.4   ,  0.7   ,  0.    ,  1.9   ,  0.076 , 11.    , 34.    ,
        0.9978,  3.51  ,  0.56  ,  9.4   ])

In [15]:
input_pred=[[7.4, 0.7, 0, 1.9, 0.076, 11, 34, 0.9978,3.51,0.56, 9.4]]

X = np.array(input_pred)
preds = loaded_model.predict_proba(X)
preds_singular = loaded_model.predict(X)
print(preds)

[[1.7881393e-05 9.9998212e-01]]


In [26]:
def makePredictions(fixed_acidity, volatile_acidity, citric_acid, 
                    residual_sugar, chlorides, free_sulfur_dioxide, total_sulfur_dioxide, density,
                   pH, sulphates, alcohol):
    
    input_pred = [[fixed_acidity, volatile_acidity, citric_acid, 
                    residual_sugar, chlorides, free_sulfur_dioxide, total_sulfur_dioxide, density,
                   pH, sulphates, alcohol]]
    
    filename = 'wine_model.h5'
    loaded_model = pickle.load(open(filename, 'rb'))

    X = np.array(input_pred)
    preds = loaded_model.predict_proba(X)[0]
    preds_singular = loaded_model.predict(X)
    
    rtn = {"prob_white": preds[0],
          "prob_red": preds[1],
          "wine_pred": "red" if preds_singular[0] == 1 else "white"}

    return rtn


In [27]:
makePredictions(7.4, 9, 0, 9, 3.5, 11, 60, 0.9978,3.51,0.56, 9.4)

{'prob_white': 0.0041326284, 'prob_red': 0.9958674, 'wine_pred': 'red'}

In [32]:
df.iloc[-1].values

array([6.0000e+00, 2.1000e-01, 3.8000e-01, 8.0000e-01, 2.0000e-02,
       2.2000e+01, 9.8000e+01, 9.8941e-01, 3.2600e+00, 3.2000e-01,
       1.1800e+01])

In [34]:
makePredictions(6.0000e+00, 2.1000e-01, 3.8000e-01, 8.0000e-01, 2.0000e-02,
       2.2000e+01, 9.8000e+01, 9.8941e-01, 3.2600e+00, 3.2000e-01,
       1.1800e+01)

{'prob_white': 0.99990183, 'prob_red': 9.8147495e-05, 'wine_pred': 'white'}